"""celeborn_cmm — codebase-memory-mcp (CMM) adapter: Sprint 1 "Zero Prompts".

Stdlib-only. This is the ENTIRE Celeborn-owned seam to CMM (the spec's §4 "adapter, not a
dependency"). Everything here is interface-level glue — it depends on CMM's public surface (its
14 MCP tool names + binary CLI) and NEVER on its internals. No code from the CMM tree is touched.

★ NORTH STAR (carry into every decision): we integrate CMM **first and foremost to preserve
vibe-coder FLOW by eliminating permission-prompt interruptions.** Token savings and code-
intelligence are real but SECONDARY. Sprint 1's job is to make structural questions answerable
through CMM's pre-cleared read-only tools with ZERO "Allow" clicks — and to *install* that
flow-first statement into the project's agent-facing instructions, not just document it here.

What S1 ships (CMM-1…CMM-5):
  • merge_cmm_permissions  — the pure, idempotent permission merge (the whole feature's safety).
  • schema_guard           — validate before writing; never emit a malformed settings file.
  • MCP-registration ensure — make CMM's server entry exist in the MCP channel (`.mcp.json`).
  • `celeborn cmm engage`  — orchestrate the above + first index + install the North Star block.
  • `celeborn cmm off`/`status` — reversible, sticky opt-out + honest readout.

Two channels, never mixed (Decision 3): the portable permission allow-list → project
`.claude/settings.json` (shareable); the machine-specific MCP server registration (binary path)
→ `.mcp.json`. We never write a binary path into settings.json.

Imported lazily by celeborn.py so the free, local core stays dependency- and network-free.
"""

from __future__ import annotations

import copy
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

import celeborn as cb  # fully loaded by the time any `cmm` command runs


# --------------------------------------------------------------------------- the §5 contract
#
# These ids are the CONTRACT with CMM (spec §5, the 14-tool classification table). A typo here
# silently fails to clear a prompt — that is the single most likely "it still prompts" bug — so
# `tests/test_celeborn.py` asserts these sets verbatim. Copy from the spec, never paraphrase.

CMM_MCP_PREFIX = "mcp__codebase-memory-mcp__"

# 11 read-only/local/no-network CMM tools + the 2 native search tools. Auto-allowed: they never
# prompt. `index_repository` is a LOCAL-only write to the graph (the engage action), not a mutation
# of the user's repo — so it earns `allow` per the §5 table.
CMM_ALLOW_TOOLS = (
    "Grep",
    "Glob",
    "mcp__codebase-memory-mcp__search_graph",
    "mcp__codebase-memory-mcp__query_graph",
    "mcp__codebase-memory-mcp__trace_path",
    "mcp__codebase-memory-mcp__get_architecture",
    "mcp__codebase-memory-mcp__get_graph_schema",
    "mcp__codebase-memory-mcp__get_code_snippet",
    "mcp__codebase-memory-mcp__search_code",
    "mcp__codebase-memory-mcp__detect_changes",
    "mcp__codebase-memory-mcp__list_projects",
    "mcp__codebase-memory-mcp__index_status",
    "mcp__codebase-memory-mcp__index_repository",
)

# The 3 mutating tools. They go to `ask` and ASK WINS — even against a broad pre-existing `allow`
# (or a wildcard). A user who allowed `delete_project` must still get prompted.
CMM_ASK_TOOLS = (
    "mcp__codebase-memory-mcp__delete_project",
    "mcp__codebase-memory-mcp__manage_adr",
    "mcp__codebase-memory-mcp__ingest_traces",
)

# The native tools we add. Provenance matters on `off`: never strip the user's OWN Grep/Glob —
# only the ones engage provably introduced (tracked in rc `cmm.added_allow`).
CMM_NATIVE_TOOLS = ("Grep", "Glob")

# All 14 CMM tools (for `/mcp`-count assertions + status), in classification order.
CMM_ALL_TOOLS = tuple(t for t in CMM_ALLOW_TOOLS if t.startswith(CMM_MCP_PREFIX)) + CMM_ASK_TOOLS

CMM_SERVER_NAME = "codebase-memory-mcp"
RC_KEY = "cmm"  # the .celebornrc block this module owns

# Managed marker block for the North Star (CMM-4). Distinct from the init block's CELEBORN markers
# so the two never collide; same idempotent regenerate-in-place pattern as `_ensure_rules_file`.
CMM_MD_BEGIN = "<!-- BEGIN CELEBORN-CMM (managed block — regenerated by `celeborn cmm engage`) -->"
CMM_MD_END = "<!-- END CELEBORN-CMM -->"


# --------------------------------------------------------------------------- CMM-1: the pure merge
#
# The whole feature's safety lives here, so it is a PURE function on a parsed `permissions` object —
# de-risked in isolation and unit-tested before it ever touches disk (mirrors how `reconcile_tasks`
# was built). No I/O, no globals mutated.

def _dedupe(seq) -> list:
    """Order-preserving dedupe."""
    seen: set = set()
    out: list = []
    for x in seq:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


def merge_cmm_permissions(existing: dict | None) -> dict:
    """Merge the §5 allow/ask block into a parsed `permissions` object and return the merged copy.

    Invariants (all unit-tested):
      • Union + preserve — every pre-existing user `allow`/`ask`/`deny` entry survives.
      • `ask` wins — the 3 mutating tools always land in `ask`; any stale copy in `allow` is
        stripped, even if the user (or a wildcard) put it there.
      • Dedupe — no duplicate ids in any bucket.
      • Idempotent — merge(merge(x)) == merge(x).
    """
    perms = copy.deepcopy(existing) if isinstance(existing, dict) else {}
    allow = list(perms.get("allow") or [])
    ask = list(perms.get("ask") or [])

    # Union: append our ids that aren't already present (preserves user entries + their order).
    allow.extend(t for t in CMM_ALLOW_TOOLS if t not in set(allow))
    ask.extend(t for t in CMM_ASK_TOOLS if t not in set(ask))

    # ask wins: strip the mutating ids out of allow (after the union, so an entry the user put in
    # allow is moved — not duplicated — into ask).
    mutating = set(CMM_ASK_TOOLS)
    allow = [a for a in allow if a not in mutating]

    perms["allow"] = _dedupe(allow)
    perms["ask"] = _dedupe(ask)
    return perms


def permission_provenance(before: dict | None, after: dict) -> dict:
    """The ids `merge_cmm_permissions` ADDED — used by `off` to revert exactly what engage added and
    nothing the user owned. Computed as the per-bucket set difference (after − before)."""
    before = before if isinstance(before, dict) else {}
    b_allow, b_ask = set(before.get("allow") or []), set(before.get("ask") or [])
    a_allow, a_ask = list(after.get("allow") or []), list(after.get("ask") or [])
    return {
        "allow_added": [x for x in a_allow if x not in b_allow],
        "ask_added": [x for x in a_ask if x not in b_ask],
    }


def revert_cmm_permissions(existing: dict | None, provenance: dict | None) -> dict:
    """Remove exactly the entries engage recorded adding (provenance), leaving user entries intact.
    Conservative by design: with no provenance, nothing is removed (never strip the user's tools)."""
    perms = copy.deepcopy(existing) if isinstance(existing, dict) else {}
    prov = provenance or {}
    drop_allow = set(prov.get("allow_added") or [])
    drop_ask = set(prov.get("ask_added") or [])
    if "allow" in perms:
        perms["allow"] = [a for a in (perms.get("allow") or []) if a not in drop_allow]
    if "ask" in perms:
        perms["ask"] = [a for a in (perms.get("ask") or []) if a not in drop_ask]
    return perms


# --------------------------------------------------------------------------- CMM-2: schema guard
#
# Validate the `permissions` schema + identifier format BEFORE any write. On mismatch we no-op
# gracefully and log a clear skip reason — we never write a malformed settings file (the AC).

# A Claude Code permission identifier: a native tool (optionally with a `(scope)` clause, e.g.
# `Bash(rg:*)`), or an MCP id `mcp__<server>__<tool>`.
_TOOL_ID_RE = re.compile(
    r"^(?:[A-Za-z][A-Za-z0-9]*(?:\([^)]*\))?"
    r"|mcp__[a-z0-9][a-z0-9_-]*__[a-z0-9_]+)$"
)


def schema_guard(existing_data: dict | None) -> tuple[bool, str | None]:
    """(ok, skip_reason). `ok` only when it is safe to write: the existing `permissions` object is
    shaped the way Claude Code expects (allow/ask/deny are lists of strings) AND every id we are
    about to write matches the known identifier format. Returns (False, reason) — never raises —
    so the caller can skip the permission write while still doing the steps that can run."""
    data = existing_data if isinstance(existing_data, dict) else {}
    perms = data.get("permissions")
    if perms is not None and not isinstance(perms, dict):
        return False, "`permissions` is not a JSON object"
    perms = perms or {}
    for bucket in ("allow", "ask", "deny"):
        val = perms.get(bucket)
        if val is None:
            continue
        if not isinstance(val, list):
            return False, f"`permissions.{bucket}` is not a list"
        if not all(isinstance(x, str) for x in val):
            return False, f"`permissions.{bucket}` contains a non-string entry"
    for tid in (*CMM_ALLOW_TOOLS, *CMM_ASK_TOOLS):
        if not _TOOL_ID_RE.match(tid):
            return False, f"tool id {tid!r} does not match the Claude Code identifier format"
    return True, None


def detect_claude_version() -> str | None:
    """Best-effort `claude --version` (informational for `status`); None if not resolvable."""
    exe = shutil.which("claude")
    if not exe:
        return None
    try:
        r = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        return None
    if r.returncode != 0:
        return None
    m = re.search(r"\d+\.\d+(?:\.\d+)?", r.stdout or "")
    return m.group(0) if m else (r.stdout.strip() or None)


# --------------------------------------------------------------------------- disk: permission write
#
# Reuse Celeborn's existing permission-writer pattern (the same read→merge→write the adapter's
# `permission_target` + `cmd_permissions` use) instead of forking a new writer. The new LOGIC stays
# here in celeborn_cmm.py; the resolution + JSON convention are core's.

def _read_json(path: Path) -> dict | None:
    """Parse a JSON file. Returns {} for a missing file, None for invalid JSON (so the caller can
    refuse to clobber a file it can't safely round-trip)."""
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def _permission_target(ctx: Path, adapter, *, global_: bool) -> Path | None:
    """Where the shareable allow-list lives. Project `.claude/settings.json` by default (§5: portable,
    committed); `~/.claude/settings.json` only on the explicit `--global` opt-in. None if the harness
    has no per-command allow-list (e.g. Grok/Codex) — engage then degrades and skips the write."""
    if global_:
        return Path.home() / ".claude" / "settings.json"
    target, how = adapter.permission_target(ctx, shared=True)
    if target is None or how != "per-command-allow":
        return None
    return target


def apply_permissions(ctx: Path, adapter, *, global_: bool) -> dict:
    """CMM-1 on disk, gated by CMM-2. Returns a result dict:
        {"status": "applied"|"skipped"|"noop"|"error", "reason", "target", "provenance"}.
    Never raises; never writes a malformed file."""
    target = _permission_target(ctx, adapter, global_=global_)
    if target is None:
        return {"status": "skipped",
                "reason": f"the '{adapter.name}' harness has no per-command allow-list to pre-clear",
                "target": None, "provenance": {}}

    data = _read_json(target)
    if data is None:
        return {"status": "error",
                "reason": f"{target} is not valid JSON — refusing to rewrite it", "target": str(target),
                "provenance": {}}

    ok_schema, why = schema_guard(data)
    if not ok_schema:
        return {"status": "skipped", "reason": f"schema guard: {why}",
                "target": str(target), "provenance": {}}

    before = dict(data.get("permissions") or {})
    merged = merge_cmm_permissions(before)
    prov = permission_provenance(before, merged)

    if merged == before and target.is_file():
        # Idempotent re-run — nothing changed.
        return {"status": "noop", "reason": None, "target": str(target), "provenance": prov}

    data["permissions"] = merged
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(data, indent=2) + "\n")
    return {"status": "applied", "reason": None, "target": str(target), "provenance": prov}


def revert_permissions(ctx: Path, adapter, provenance: dict, *, global_: bool) -> dict:
    """Undo apply_permissions using the recorded provenance — removes only what engage added."""
    target = _permission_target(ctx, adapter, global_=global_)
    if target is None or not target.is_file():
        return {"status": "noop", "reason": "no allow-list file to revert", "target": None}
    data = _read_json(target)
    if data is None:
        return {"status": "error", "reason": f"{target} is not valid JSON", "target": str(target)}
    before = dict(data.get("permissions") or {})
    reverted = revert_cmm_permissions(before, provenance)
    if reverted == before:
        return {"status": "noop", "reason": None, "target": str(target)}
    data["permissions"] = reverted
    target.write_text(json.dumps(data, indent=2) + "\n")
    return {"status": "reverted", "reason": None, "target": str(target)}


# --------------------------------------------------------------------------- CMM-3: MCP registration
#
# The MACHINE-SPECIFIC channel (Decision 3). The CMM server entry (a binary path) belongs in
# `.mcp.json`, never in the portable settings.json. Reuse CMM's own config writer where we can.

def cmm_binary() -> str | None:
    """Resolve the CMM binary: $CELEBORN_CMM_BIN, else the S2 provisioned cache (pinned, verified),
    else `codebase-memory-mcp`/`cmm` on PATH. None if CMM isn't installed anywhere — every caller
    degrades gracefully on None (Decision 6)."""
    env = (os.environ.get("CELEBORN_CMM_BIN") or "").strip()
    if env and Path(env).exists():
        return env
    # S2 "Zero Touch": a pinned binary auto-provisioned into the cache needs no PATH install. Import
    # lazily + defensively so a provisioning module problem can never break S1's resolution.
    try:
        cached = __import__("celeborn_cmm_provision").resolve_cached_binary()
        if cached:
            return cached
    except Exception:
        pass
    for name in (CMM_SERVER_NAME, "cmm"):
        found = shutil.which(name)
        if found:
            return found
    return None


def _mcp_config_path(ctx: Path) -> Path:
    return ctx.parent / ".mcp.json"


def mcp_registered(ctx: Path) -> bool:
    data = _read_json(_mcp_config_path(ctx))
    if not data:
        return False
    return CMM_SERVER_NAME in (data.get("mcpServers") or {})


def ensure_mcp_registration(ctx: Path) -> dict:
    """Make sure CMM's MCP server entry exists in the project `.mcp.json`.

    We deliberately DON'T shell out to CMM's own `install` verb: verified against the real binary
    (HEAD e599df1), `install` is GLOBAL and invasive — it rewrites `~/.claude/.mcp.json`,
    `~/.claude.json`, `~/.bashrc` PATH and configures every detected agent (Codex/Cursor/VS Code/…).
    That violates Celeborn's project-scoped, reversible principle. Instead we hand-author the single
    surgical entry the spec wants (Decision 3) in the project `.mcp.json`, and only there. Users who
    want the full global multi-agent setup can still run `codebase-memory-mcp install` themselves.

    Invocation contract: the bare binary (no args) runs the MCP server on stdio, so the entry is
    `{"command": <bin>, "args": []}` — NOT a `--mcp`-style flag. Degrades cleanly when CMM is absent."""
    path = _mcp_config_path(ctx)
    if mcp_registered(ctx):
        return {"status": "noop", "reason": "already registered", "path": str(path)}

    binary = cmm_binary()
    if not binary:
        return {"status": "skipped",
                "reason": "CMM binary not found (set $CELEBORN_CMM_BIN or run `celeborn cmm provision`)",
                "path": str(path)}

    # Hand-author the entry in the MCP channel (never in settings.json). Preserve any existing
    # mcpServers the user already has.
    data = _read_json(path) or {}
    if not isinstance(data, dict):
        data = {}
    servers = data.setdefault("mcpServers", {})
    servers[CMM_SERVER_NAME] = {"command": binary, "args": []}
    path.write_text(json.dumps(data, indent=2) + "\n")
    return {"status": "registered", "reason": "wrote project .mcp.json entry", "path": str(path)}


def _parse_index_result(stdout: str) -> dict | None:
    """Extract CMM's index_repository JSON result from stdout. The binary emits human `level=…` log
    lines (on stderr, but be defensive) plus a single JSON object; return the first line that parses
    as JSON, or None if none does."""
    for line in (stdout or "").splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            obj = json.loads(line)
        except (json.JSONDecodeError, ValueError):
            continue
        if isinstance(obj, dict):
            return obj
    return None


def index_repository(ctx: Path) -> dict:
    """Kick off the first structural index (the engage action) via the real CLI contract, verified
    against the binary: `<bin> cli index_repository '{"repo_path": <root>}'`. Best-effort: if the
    binary is absent or the call fails, degrade per Decision 6 — log and continue, never error."""
    binary = cmm_binary()
    if not binary:
        return {"status": "skipped", "reason": "CMM binary not found — structure not indexed yet"}
    payload = json.dumps({"repo_path": str(ctx.parent)})
    try:
        r = subprocess.run([binary, "cli", "index_repository", payload],
                           capture_output=True, text=True, timeout=300)
    except (OSError, subprocess.SubprocessError) as e:
        return {"status": "error", "reason": f"index call failed: {e}"}
    result = _parse_index_result(r.stdout)
    if r.returncode == 0 and result and result.get("status") == "indexed":
        n, e = result.get("nodes"), result.get("edges")
        detail = f"{n} nodes / {e} edges" if n is not None else "ok"
        return {"status": "indexed", "reason": detail, "project": result.get("project")}
    why = (result or {}).get("error") or (r.stderr or "").strip()[:200] or "non-zero exit"
    return {"status": "error", "reason": f"index_repository failed: {why}"}


# --------------------------------------------------------------------------- CMM-4: North Star install
#
# Install the flow-first North Star into the project's AGENT-FACING instructions — not just the
# planning docs. A managed marker block (idempotent, regenerate-in-place) in CLAUDE.md + AGENTS.md,
# plus the installed skill snippet if one is present. The AC for CMM-4 is satisfied only when the
# *installed* instructions contain the statement.

def _north_star_body() -> str:
    return (
        "## Code-structure memory (CMM) — flow is primary\n\n"
        "★ **North Star:** this project has code-structure memory "
        "(`codebase-memory-mcp`) engaged **first and foremost to preserve flow by eliminating "
        "permission-prompt interruptions.** Token savings and code-intelligence are real but "
        "**secondary** — when a tradeoff arises, optimize for *fewer interruptions / uninterrupted "
        "flow*.\n\n"
        "Answer structural questions (call chains, impact, routes, dead code, \"where is X "
        "defined/used\") through the pre-cleared `mcp__codebase-memory-mcp__*` read-only tools and "
        "native `Grep`/`Glob` — these are allow-listed and never prompt. **Avoid Bash "
        "`grep`/`rg`/`find`/`cat` for structure:** each shell-out triggers an Allow prompt that "
        "breaks flow, which is exactly what CMM exists to prevent. The 3 mutating CMM tools "
        "(`delete_project`, `manage_adr`, `ingest_traces`) still prompt by design.\n"
    )


def _cmm_md_block() -> str:
    return f"{CMM_MD_BEGIN}\n{_north_star_body()}{CMM_MD_END}\n"


def install_north_star(root: Path) -> list[str]:
    """Write/refresh the North Star managed block into CLAUDE.md + AGENTS.md (+ a skill snippet if
    an installed Celeborn skill is found). Idempotent. Returns the files written."""
    written: list[str] = []
    for filename in ("CLAUDE.md", "AGENTS.md"):
        # Augment only rules files that already exist — never CREATE one. This keeps the North Star
        # from resurrecting a CLAUDE.md/AGENTS.md the user opted out of (`init --no-claude-md` /
        # `--no-agents-md`); the rules file is owned by init, the block only rides along.
        if not (root / filename).exists():
            continue
        if cb._ensure_rules_file(root, filename, CMM_MD_BEGIN, CMM_MD_END, _cmm_md_block):
            written.append(filename)
    # Best-effort skill snippet: annotate an installed Celeborn skill's SKILL.md if present.
    for skill_md in sorted((root / ".claude" / "skills").glob("*/SKILL.md")):
        try:
            text = skill_md.read_text()
        except OSError:
            continue
        if "celeborn" not in text.lower():
            continue
        if cb._ensure_rules_file(skill_md.parent, "SKILL.md", CMM_MD_BEGIN, CMM_MD_END, _cmm_md_block):
            written.append(str(skill_md.relative_to(root)))
    return written


def remove_north_star(root: Path) -> list[str]:
    """Strip the North Star managed block from any file engage wrote it to. Idempotent."""
    removed: list[str] = []
    candidates = [root / "CLAUDE.md", root / "AGENTS.md"]
    candidates += list((root / ".claude" / "skills").glob("*/SKILL.md"))
    for path in candidates:
        if not path.is_file():
            continue
        text = path.read_text()
        if CMM_MD_BEGIN not in text or CMM_MD_END not in text:
            continue
        start = text.index(CMM_MD_BEGIN)
        stop = text.index(CMM_MD_END) + len(CMM_MD_END)
        new = (text[:start] + text[stop:]).rstrip("\n")
        new = (new + "\n") if new else ""
        path.write_text(new)
        removed.append(path.name)
    return removed


# --------------------------------------------------------------------------- rc state (provenance)

def _cmm_state(ctx: Path) -> dict:
    block = cb.load_config(ctx).get(RC_KEY)
    return dict(block) if isinstance(block, dict) else {}


def _save_cmm_state(ctx: Path, state: dict) -> None:
    cb._update_config(ctx, **{RC_KEY: state})


def credited_tool_names(ctx: Path) -> set:
    """The tool names whose calls count as a "prompt auto-allowed" for this project — exactly what
    engage pre-cleared (the recorded provenance), and ONLY while CMM is engaged and not opted out.

    Provenance is the right gate: it credits only tools engage actually added, so the user's OWN
    pre-existing `Grep`/`Glob` never inflate the figure, and a project that never engaged accrues
    nothing. Each observed call to one of these is a structural query that ran without an
    "Allow"/"Always allow" prompt — the flow-preserving win we measure (the North Star)."""
    state = _cmm_state(ctx)
    if not state.get("engaged") or state.get("opted_out"):
        return set()
    return set(state.get("added_allow") or [])


# --------------------------------------------------------------------------- auto-engage on init
#
# Celeborn's design goal (this is the product call): EVERY project Celeborn scaffolds should come with
# CMM engaged, because the flow win — fewer "Allow" prompts, so the human stops being the bottleneck —
# is what makes the difference. So `celeborn init` auto-engages by default, opt-out and reversible.

def _env_opt_out() -> bool:
    """True if $CELEBORN_NO_CMM is set to a truthy value (presence with a non-falsey value)."""
    v = (os.environ.get("CELEBORN_NO_CMM") or "").strip().lower()
    return v not in ("", "0", "false", "no", "off")


def engage_on_init(ctx: Path, adapter, *, no_provision: bool = False) -> dict:
    """The same engage building blocks as `cmm engage`, run quietly for `celeborn init` and returning
    a structured summary (init prints a concise version). Respects a sticky opt-out; the permission
    pre-clear lands regardless of whether the CMM binary is installed (pre-clearing Grep/Glob is an
    immediate flow win, and the CMM tool entries are inert until CMM is present); index runs only when
    a binary is available. Best-effort throughout — never raises, always degrades (Decision 6)."""
    state = _cmm_state(ctx)
    if state.get("opted_out"):
        return {"status": "opted_out"}

    res: dict = {"status": "engaged", "skipped": []}

    perm = apply_permissions(ctx, adapter, global_=False)
    res["permission"] = perm
    if perm["status"] == "applied":
        state["added_allow"] = perm["provenance"].get("allow_added", [])
        state["added_ask"] = perm["provenance"].get("ask_added", [])
    elif perm["status"] not in ("applied", "noop"):
        res["skipped"].append(f"permissions ({perm['reason']})")

    if not no_provision and cmm_binary() is None:
        try:
            res["provision"] = __import__("celeborn_cmm_provision").provision()
        except Exception as e:  # noqa: BLE001
            res["provision"] = {"status": "error", "reason": f"{type(e).__name__}: {e}"}

    res["binary_present"] = cmm_binary() is not None

    mcp = ensure_mcp_registration(ctx)
    res["mcp"] = mcp
    if mcp["status"] not in ("registered", "noop"):
        res["skipped"].append(f"mcp ({mcp['reason']})")

    idx = index_repository(ctx)
    res["index"] = idx
    if idx["status"] == "indexed":
        state["indexed"] = True
    else:
        res["skipped"].append(f"index ({idx['reason']})")

    res["north_star"] = install_north_star(ctx.parent)

    state["engaged"] = True
    state["opted_out"] = False
    state["scope"] = "project"
    state["engaged_at"] = cb.now_iso()
    _save_cmm_state(ctx, state)
    return res


def maybe_engage_on_init(args, ctx: Path) -> None:
    """Tail of `celeborn init`. Default-on CMM engage unless opted out (`--no-cmm`, $CELEBORN_NO_CMM,
    or a sticky per-project opt-out). Prints a concise summary; when the CMM binary is absent, prints
    the install recommendation (the structural half needs it). Wrapped so init never fails on CMM."""
    if getattr(args, "no_cmm", False) or _env_opt_out():
        return
    try:
        adapter = cb.active_adapter(ctx, getattr(args, "harness", None))
        res = engage_on_init(ctx, adapter)
    except Exception:
        return  # init must never break on CMM
    if res.get("status") == "opted_out":
        return
    if (res.get("permission") or {}).get("status") in ("applied", "noop"):
        cb.ok("CMM engaged for this project — read-only structural tools + Grep/Glob pre-cleared "
              "(fewer 'Allow' prompts = less waiting on you). Reverse with `celeborn cmm off`.")
    if res.get("binary_present"):
        idx = res.get("index") or {}
        if idx.get("status") == "indexed":
            cb.ok(f"CMM indexed this repo ({idx.get('reason')}).")
    else:
        cb.info("Recommended: install CMM for the structural half (zero-prompt code queries) — "
                "https://github.com/DeusData/codebase-memory-mcp  (then it engages automatically). "
                "Opt out per project with `celeborn init --no-cmm` or `CELEBORN_NO_CMM=1`.")


# --------------------------------------------------------------------------- the command surface

def cmd_cmm(args):
    """Dispatch `celeborn cmm <engage|off|status>`."""
    action = getattr(args, "cmm_cmd", None)
    if action == "engage":
        return _cmd_engage(args)
    if action == "off":
        return _cmd_off(args)
    if action == "status":
        return _cmd_status(args)
    cb.die(f"unknown cmm command: {action!r}")


def _cmd_engage(args):
    ctx = cb.require_context(args)
    root = ctx.parent
    adapter = cb.active_adapter(ctx, getattr(args, "harness", None))
    global_ = getattr(args, "global_", False)
    state = _cmm_state(ctx)

    if state.get("opted_out") and not getattr(args, "force", False):
        cb.warn("CMM is opted out for this project (`celeborn cmm off` set a sticky marker). "
                "Re-engage with: celeborn cmm engage --force")
        return

    skipped: list[str] = []

    # CMM-1 (gated by CMM-2): the permission pre-clear — the headline. This must land even if the
    # rest degrades (Decision 6).
    perm = apply_permissions(ctx, adapter, global_=global_)
    if perm["status"] in ("applied", "noop"):
        # Record provenance only on a real apply; preserve prior provenance on a noop re-run.
        if perm["status"] == "applied":
            state["added_allow"] = perm["provenance"].get("allow_added", [])
            state["added_ask"] = perm["provenance"].get("ask_added", [])
        cb.ok(f"Permission pre-clear {'applied' if perm['status']=='applied' else 'already present'}: "
              f"{perm['target']}")
    else:
        skipped.append(f"permission pre-clear ({perm['reason']})")
        cb.warn(f"Permission pre-clear skipped — {perm['reason']}")

    # S2 (CMM-6): auto-provision the pinned binary so engage needs no manual install. Best-effort
    # and gated — `--no-provision` opts out, and any failure degrades (Decision 6 / CMM-10): the
    # permission pre-clear above has already landed, so the session is never blocked.
    if not getattr(args, "no_provision", False) and cmm_binary() is None:
        try:
            prov = __import__("celeborn_cmm_provision").provision()
        except Exception as e:  # noqa: BLE001 — provisioning must never break engage
            prov = {"status": "error", "reason": f"{type(e).__name__}: {e}"}
        if prov["status"] in ("provisioned", "cached"):
            cb.ok(f"CMM binary {'provisioned' if prov['status']=='provisioned' else 'present'} "
                  f"({prov.get('version')} · {prov.get('path')})")
        else:
            skipped.append(f"provision ({prov['reason']})")
            cb.warn(f"Auto-provision skipped — {prov['reason']}")

    # CMM-3: MCP server registration (the machine-specific channel).
    mcp = ensure_mcp_registration(ctx)
    if mcp["status"] in ("registered", "noop"):
        cb.ok(f"MCP server '{CMM_SERVER_NAME}' {'registered' if mcp['status']=='registered' else 'present'} "
              f"({mcp['path']})")
    else:
        skipped.append(f"MCP registration ({mcp['reason']})")
        cb.warn(f"MCP registration skipped — {mcp['reason']}")

    # First structural index (best-effort; degrade if CMM absent).
    idx = index_repository(ctx)
    if idx["status"] == "indexed":
        cb.ok(f"Structural index started ({idx['reason']})")
        state["indexed"] = True
    else:
        skipped.append(f"index ({idx['reason']})")
        cb.warn(f"Index skipped — {idx['reason']}")

    # CMM-4: install the North Star into the project's agent-facing instructions.
    ns = install_north_star(root)
    if ns:
        cb.ok(f"North Star installed → {', '.join(ns)}")
    else:
        cb.info("North Star already present in agent instructions")

    # Persist engage state + provenance.
    state["engaged"] = True
    state["opted_out"] = False
    state["scope"] = "global" if global_ else "project"
    state["engaged_at"] = cb.now_iso()
    _save_cmm_state(ctx, state)

    # §8 one-line transparency notice.
    print("🏹 Celeborn —> This project's big enough that I've switched on code-structure memory "
          "(and cleared the related permission prompts) to keep you in flow.")
    if skipped:
        cb.info("Engaged with degraded parts (S1 assumes CMM is installed for the index/query half): "
                + "; ".join(skipped))


def _cmd_off(args):
    ctx = cb.require_context(args)
    root = ctx.parent
    adapter = cb.active_adapter(ctx, getattr(args, "harness", None))
    state = _cmm_state(ctx)
    global_ = state.get("scope") == "global" or getattr(args, "global_", False)

    provenance = {"allow_added": state.get("added_allow") or [],
                  "ask_added": state.get("added_ask") or []}
    rev = revert_permissions(ctx, adapter, provenance, global_=global_)
    if rev["status"] == "reverted":
        cb.ok(f"Reverted CMM permission entries in {rev['target']}")
    elif rev["status"] == "error":
        cb.warn(f"Permission revert skipped — {rev['reason']}")
    else:
        cb.info("No CMM permission entries to revert")

    removed = remove_north_star(root)
    if removed:
        cb.ok(f"Removed North Star block from {', '.join(removed)}")

    # Sticky per-project opt-out: survives re-runs; engage requires --force to override.
    state["engaged"] = False
    state["opted_out"] = True
    state["added_allow"] = []
    state["added_ask"] = []
    state["off_at"] = cb.now_iso()
    _save_cmm_state(ctx, state)
    cb.ok("CMM disengaged for this project (sticky opt-out set). Re-engage: celeborn cmm engage --force")


def _cmd_status(args):
    ctx = cb.require_context(args)
    adapter = cb.active_adapter(ctx, getattr(args, "harness", None))
    state = _cmm_state(ctx)
    global_ = state.get("scope") == "global" or getattr(args, "global_", False)

    binary = cmm_binary()
    target = _permission_target(ctx, adapter, global_=global_)
    allow_present = ask_present = False
    if target is not None:
        data = _read_json(target) or {}
        perms = data.get("permissions") or {}
        allow_set = set(perms.get("allow") or [])
        ask_set = set(perms.get("ask") or [])
        allow_present = all(t in allow_set for t in CMM_ALLOW_TOOLS)
        ask_present = all(t in ask_set for t in CMM_ASK_TOOLS)

    # S2: surface the pin + whether the binary is the auto-provisioned one (best-effort).
    pin_version = provisioned = None
    try:
        prov = __import__("celeborn_cmm_provision")
        pin_version = prov.load_pin().get("version")
        provisioned = prov.resolve_cached_binary()
    except Exception:
        pass

    doc = {
        "engaged": bool(state.get("engaged")),
        "opted_out": bool(state.get("opted_out")),
        "indexed": bool(state.get("indexed")),
        "scope": state.get("scope") or ("global" if global_ else "project"),
        "cmm_installed": binary is not None,
        "cmm_binary": binary,
        "pin_version": pin_version,
        "provisioned": provisioned is not None,
        "mcp_registered": mcp_registered(ctx),
        "allow_list_present": allow_present,
        "ask_list_present": ask_present,
        "permission_target": str(target) if target else None,
        "claude_version": detect_claude_version(),
        "engaged_at": state.get("engaged_at"),
    }
    if getattr(args, "json", False):
        print(json.dumps(doc, indent=2))
        return

    def yn(b):
        return "yes" if b else "no"

    print(f"🏹 Celeborn CMM status ({adapter.name})")
    print(f"  engaged:           {yn(doc['engaged'])}" + ("  ⛔ opted out" if doc["opted_out"] else ""))
    print(f"  CMM installed:     {yn(doc['cmm_installed'])}"
          + (f"  ({binary})" if binary else "  — `celeborn cmm provision` once the pin is finalized"))
    print(f"  pin / provisioned: {doc['pin_version'] or '—'} / {yn(doc['provisioned'])}")
    print(f"  MCP registered:    {yn(doc['mcp_registered'])}")
    print(f"  structure indexed: {yn(doc['indexed'])}")
    print(f"  allow-list ({len(CMM_ALLOW_TOOLS)}):   {yn(doc['allow_list_present'])}"
          + (f"   → {doc['permission_target']}" if doc["permission_target"] else "   (no per-command allow-list on this harness)"))
    print(f"  ask-list ({len(CMM_ASK_TOOLS)} mutating): {yn(doc['ask_list_present'])}")
    if doc["claude_version"]:
        print(f"  Claude Code:       {doc['claude_version']}")
    if not doc["cmm_installed"]:
        cb.info("CMM binary not found — the permission pre-clear still lands; install "
                "codebase-memory-mcp (or set $CELEBORN_CMM_BIN) for the index/query half. S2 automates this.")
