#!/usr/bin/env python3
"""Codex CLI adapter for Celeborn — bridges Codex hooks/rollouts to the stock CLI.

Mirrors the Grok bridge (`grok/scripts/grok_celeborn.py`) and does **not** modify Celeborn
core. It converts Codex rollout session files (`~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl`)
into the Claude Code JSONL shape that `celeborn capture` expects, normalizes Codex's
tool/function vocabulary into the canonical names, and dispatches hook events without
`$CELEBORN_HOME` or `hookSpecificOutput`.

The four adapter-contract responsibilities (see plan/t70-skill-advisor.md) are fulfilled here,
at the bridge level, exactly as the Grok bridge fulfills them:

  * friction_signals  — `cmd_advise` reads ~/.codex/config.toml and flags an interactive,
                         untrusted workspace as canonical `permission-friction`.
  * permission_target — `~/.codex/config.toml` (coarse approval/sandbox + per-project trust),
                         not a per-command allow-list.
  * render            — Codex idiom: a config.toml trust/approval hint (cmd_permissions).
  * inject            — AGENTS.md managed block + `.codex-orient-pending.md` (Codex auto-loads
                         AGENTS.md every session; it does not inject SessionStart stdout).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import uuid
from pathlib import Path

MODULE_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = MODULE_ROOT / "cache"
ORIENT_FILE = ".codex-orient-pending.md"

AGENTS_BEGIN = "<!-- BEGIN CELEBORN (managed — regenerated by `celeborn init` / codex_celeborn.py sync-agents) -->"
AGENTS_END = "<!-- END CELEBORN -->"

# Codex renewal: the TUI starts a fresh conversation with `/new`. SessionStart re-orients via
# this adapter on the next session.
CODEX_RENEW_CMD = "/new"

# Codex's function/tool vocabulary → canonical (Claude) tool names. Codex has NO dedicated read
# tool (reads go through a shell); `apply_patch` does create/update/delete, mapped to Edit (the
# converter promotes a pure-create patch to Write). See codex-rs/core/src/tools/handlers/*.
_TOOL_MAP = {
    "shell": "Bash",
    "shell_command": "Bash",
    "local_shell": "Bash",
    "exec_command": "Bash",
    "write_stdin": "Bash",
    "container.exec": "Bash",
    "apply_patch": "Edit",
    "view_image": "Read",
    "update_plan": "Task",
    # Pass canonical names through unchanged so a future Codex tool that already matches works.
    "Bash": "Bash",
    "Read": "Read",
    "Edit": "Edit",
    "Write": "Write",
}

_SKIP_PAYLOAD = frozenset({"reasoning"})

ORIENT_NUDGE = (
    "[Celeborn orient — REQUIRED before you reply; tagged SURFACE AND OBEY]\n"
    "Read `.context/.codex-orient-pending.md` once (full `celeborn status` Hot tier), orient from "
    "it, then delete it. If missing, run `celeborn status` from the project root below.\n"
    "Project root: {root}\n"
    "Kanban shorthand HERE: `wire tN` / `claim tN` = take card tN; `ship tN` = close it; "
    "`hydrate` = orient. Cards: `.context/tasks.md`."
)

PRECOMPACT_MSG = (
    "[celeborn] Compaction imminent. CHECKPOINT now before context is summarized:\n"
    "  1. Rewrite .context/state.md in place (Now / Next action / Open threads).\n"
    "  2. Append one entry to the bottom of .context/journal.md (what + evidence + next).\n"
    "  3. Update .context/session.json (focus, next_action, branch, status, updated_at).\n"
    "Anything not written to .context/ will be lost on compaction."
)


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))


def read_stdin_json() -> dict:
    try:
        raw = sys.stdin.read()
    except OSError:
        return {}
    if not raw.strip():
        return {}
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return {}
    return data if isinstance(data, dict) else {}


def session_id(payload: dict) -> str:
    return (
        payload.get("session_id")
        or payload.get("sessionId")
        or payload.get("conversation_id")
        or payload.get("conversationId")
        or payload.get("thread_id")
        or payload.get("threadId")
        or payload.get("thread-id")
        or os.environ.get("CODEX_SESSION_ID")
        or os.environ.get("CODEX_THREAD_ID")
        or ""
    )


def workspace_root(payload: dict) -> Path:
    for key in ("workspaceRoot", "workspace_root", "cwd"):
        val = payload.get(key)
        if val:
            return Path(val).resolve()
    env = os.environ.get("CODEX_WORKSPACE_ROOT")
    if env:
        return Path(env).resolve()
    return Path.cwd().resolve()


def find_context_root(start: Path) -> Path | None:
    cur = start.resolve()
    for _ in range(32):
        if (cur / ".context").is_dir():
            return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    return None


def find_rollout_file(sid: str, root: Path | None = None) -> Path | None:
    """Locate a session's rollout transcript. Codex names them
    `~/.codex/sessions/YYYY/MM/DD/rollout-<ts>-<conversation_id>.jsonl`; we match the trailing
    conversation id (a UUID). Newest match wins."""
    if not sid:
        return None
    base = codex_home() / "sessions"
    if not base.is_dir():
        return None
    matches = sorted(base.glob(f"**/rollout-*-{sid}.jsonl"))
    if matches:
        return matches[-1]
    # Fall back to any rollout whose filename contains the id (defensive).
    loose = sorted(base.glob(f"**/*{sid}*.jsonl"))
    return loose[-1] if loose else None


def run_celeborn(
    *args: str,
    project: Path | None = None,
    cwd: Path | None = None,
    check: bool = False,
) -> subprocess.CompletedProcess:
    """Invoke celeborn. Global --path must precede the subcommand."""
    cmd = ["celeborn"]
    if project is not None:
        cmd.extend(["--path", str(project)])
    cmd.extend(args)
    # Tell core which harness is driving so active_adapter() resolves CodexAdapter (Codex-flavored
    # advisor renders + the config.toml permission lever) instead of falling back to Claude.
    env = {**os.environ, "CELEBORN_HARNESS": "codex"}
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
        check=check,
        env=env,
    )


# --------------------------------------------------------------------------- transcript convert

def map_tool_name(name: str) -> str:
    return _TOOL_MAP.get(name or "", name or "Tool")


def _content_text(content) -> str:
    """Flatten a Codex message `content` (a list of {type, text} blocks, or a plain string)."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict):
                # input_text / output_text / text all carry a `text`; refusals carry `refusal`.
                txt = block.get("text") or block.get("refusal")
                if txt:
                    parts.append(txt)
            elif isinstance(block, str):
                parts.append(block)
        return "\n".join(parts)
    return ""


def parse_tool_arguments(name: str, arguments) -> dict:
    """Codex `function_call.arguments` is a JSON-encoded STRING (Responses API). Normalize it into
    a Claude-style tool `input` dict and map the common keys to the canonical field names."""
    if isinstance(arguments, dict):
        inp = dict(arguments)
    elif isinstance(arguments, str) and arguments.strip():
        try:
            parsed = json.loads(arguments)
            inp = parsed if isinstance(parsed, dict) else {"value": parsed}
        except json.JSONDecodeError:
            inp = {"raw": arguments}
    else:
        inp = {}
    low = (name or "").lower()
    if low in ("shell", "shell_command", "local_shell", "exec_command", "container.exec"):
        cmd = inp.get("command")
        if isinstance(cmd, list):                    # `shell` takes command as an array
            inp["command"] = " ".join(str(c) for c in cmd)
        elif "command" not in inp:
            for key in ("cmd", "input"):
                if key in inp:
                    inp["command"] = inp[key]
                    break
    if low == "apply_patch" and "file_path" not in inp:
        # apply_patch carries a patch envelope; surface a best-effort path for capture context.
        patch = inp.get("patch") or inp.get("input") or ""
        m = re.search(r"\*\*\*\s+(?:Add|Update|Delete) File:\s+(.+)", str(patch))
        if m:
            inp["file_path"] = m.group(1).strip()
    return inp


def _is_pure_create_patch(inp: dict) -> bool:
    patch = str(inp.get("patch") or inp.get("input") or "")
    return "*** Add File:" in patch and "*** Update File:" not in patch and "*** Delete File:" not in patch


def convert_codex_transcript(src: Path, sid: str, dest: Path) -> int:
    """Convert a Codex rollout .jsonl → Claude Code JSONL. Returns the line count written.

    Codex rollout lines wrap a `ResponseItem` in `{type:"response_item", payload:{...}}`; messages,
    function calls and their outputs are SEPARATE lines (unlike Grok's nested tool_calls). Each is
    emitted as its own Claude-shaped line so `celeborn capture` counts tools + text identically."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with src.open("r", encoding="utf-8", errors="ignore") as fin, dest.open("w", encoding="utf-8") as fout:
        for line in fin:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            # Descend one level: rollout line → ResponseItem payload.
            if obj.get("type") == "response_item":
                item = obj.get("payload") or {}
            elif obj.get("type") in ("message", "function_call", "function_call_output",
                                     "local_shell_call", "reasoning"):
                item = obj                              # already a bare ResponseItem
            else:
                continue                                # session_meta / event_msg / turn_context / compacted
            ptype = item.get("type")
            if ptype in _SKIP_PAYLOAD:
                continue

            if ptype == "message":
                role = item.get("role") or "assistant"
                text = _content_text(item.get("content")).strip()
                if not text:
                    continue
                if role == "user":
                    out = {"type": "user", "uuid": str(uuid.uuid4()), "sessionId": sid,
                           "message": {"role": "user", "content": text}}
                else:
                    out = {"type": "assistant", "uuid": str(uuid.uuid4()), "sessionId": sid,
                           "message": {"role": "assistant",
                                       "content": [{"type": "text", "text": text}]}}
                fout.write(json.dumps(out, ensure_ascii=False) + "\n")
                count += 1
                continue

            if ptype in ("function_call", "local_shell_call"):
                if ptype == "local_shell_call":
                    raw_name = "local_shell"
                    action = item.get("action") or {}
                    args = {"command": action.get("command") or action.get("cmd") or ""}
                else:
                    raw_name = item.get("name") or ""
                    args = item.get("arguments")
                name = map_tool_name(raw_name)
                inp = parse_tool_arguments(raw_name, args)
                if name == "Edit" and _is_pure_create_patch(inp):
                    name = "Write"
                out = {"type": "assistant", "uuid": str(uuid.uuid4()), "sessionId": sid,
                       "message": {"role": "assistant", "content": [{
                           "type": "tool_use",
                           "id": item.get("call_id") or str(uuid.uuid4()),
                           "name": name, "input": inp}]}}
                fout.write(json.dumps(out, ensure_ascii=False) + "\n")
                count += 1
                continue

            if ptype == "function_call_output":
                tid = item.get("call_id") or ""
                output = item.get("output")
                if isinstance(output, dict):
                    content = output.get("content")
                    if content is None:
                        content = json.dumps(output, ensure_ascii=False)
                else:
                    content = output
                content = _content_text(content) if isinstance(content, list) else str(content or "")
                out = {"type": "user", "uuid": str(uuid.uuid4()), "sessionId": sid,
                       "toolUseResult": {"stdout": content, "stderr": ""},
                       "message": {"role": "user", "content": [
                           {"type": "tool_result", "tool_use_id": tid, "content": content}]}}
                fout.write(json.dumps(out, ensure_ascii=False) + "\n")
                count += 1
    return count


def read_context_tokens(rollout: Path | None) -> int | None:
    """Best-effort context-token read from a rollout file's token-usage events. Codex emits usage in
    `event_msg` lines (e.g. a token-count event); we take the last total we can find. Returns None
    when no usage is recorded — the caller then degrades gracefully (skips the token reminder)."""
    if rollout is None or not rollout.is_file():
        return None
    last = None
    try:
        with rollout.open("r", encoding="utf-8", errors="ignore") as fin:
            for line in fin:
                line = line.strip()
                if not line or '"token' not in line.lower() and '"usage"' not in line.lower():
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    continue
                payload = obj.get("payload") if isinstance(obj, dict) else None
                blob = payload if isinstance(payload, dict) else obj
                val = _extract_token_total(blob)
                if val is not None:
                    last = val
    except OSError:
        return None
    return last


def _extract_token_total(blob: dict) -> int | None:
    if not isinstance(blob, dict):
        return None
    for key in ("total_token_usage", "token_usage", "usage", "info"):
        sub = blob.get(key)
        if isinstance(sub, dict):
            got = _extract_token_total(sub)
            if got is not None:
                return got
    for key in ("total_tokens", "context_tokens_used", "contextTokensUsed", "total"):
        v = blob.get(key)
        if isinstance(v, (int, float)) and v > 0:
            return int(v)
    inp = blob.get("input_tokens")
    out = blob.get("output_tokens")
    if isinstance(inp, (int, float)) or isinstance(out, (int, float)):
        return int((inp or 0) + (out or 0)) or None
    return None


def claude_transcript_path(sid: str) -> Path:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    return CACHE_DIR / f"{sid}.claude.jsonl"


# --------------------------------------------------------------------------- AGENTS.md (inject)

def agents_md_block(root: Path) -> str:
    """The managed Celeborn block Codex auto-loads from the repo's AGENTS.md every session."""
    return (
        f"{AGENTS_BEGIN}\n"
        "# Celeborn — long-term memory for this repo\n\n"
        "**Memory:** `.context/` in this repository (orient from `state.md` + `session.json`).\n\n"
        "## Every Codex session — orient FIRST\n\n"
        "Codex does not inject SessionStart hook stdout into the model. Orient is **your first\n"
        "action** before replying:\n\n"
        "1. If `.context/.codex-orient-pending.md` exists → read it once, orient, then **delete it**.\n"
        "2. Else → run `celeborn status` from this repository.\n\n"
        "## Kanban shorthand (this project only)\n\n"
        "| You say | Celeborn does |\n"
        "|---|---|\n"
        "| `wire tN` / `claim tN` | `celeborn claim tN --by <you>` then implement |\n"
        "| `ship tN` | `celeborn ship tN` |\n"
        "| `hydrate` / `orient` | Read the orient-pending file or run `celeborn status` |\n\n"
        "Cards live in `.context/tasks.md`.\n"
        f"{AGENTS_END}\n"
    )


def ensure_agents_md(root: Path) -> bool:
    """Write or refresh the managed Celeborn block in `<root>/AGENTS.md`, preserving any other
    content. Returns True when the file changed."""
    path = root / "AGENTS.md"
    block = agents_md_block(root)
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
        if AGENTS_BEGIN in existing and AGENTS_END in existing:
            start = existing.index(AGENTS_BEGIN)
            stop = existing.index(AGENTS_END) + len(AGENTS_END)
            new = existing[:start] + block.rstrip("\n") + existing[stop:]
            if new == existing:
                return False
            path.write_text(new, encoding="utf-8")
            return True
        # Append below existing content.
        sep = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
        path.write_text(existing + sep + block, encoding="utf-8")
        return True
    path.write_text(block, encoding="utf-8")
    return True


# --------------------------------------------------------------------------- permission lever

def codex_config_path() -> Path:
    return codex_home() / "config.toml"


def codex_permission_status(root: Path) -> dict:
    """Read the coarse Codex permission lever from ~/.codex/config.toml WITHOUT a TOML parser
    (stdlib-only, tolerant of any layout): the global `approval_policy` / `sandbox_mode`, and whether
    THIS project is marked trusted via a `[projects."<root>"]` table with `trust_level = "trusted"`.
    Interactive (untrusted/on-request/on-failure) + not-trusted ⇒ the workspace still re-prompts."""
    cfg = codex_config_path()
    status = {"config": str(cfg), "exists": cfg.is_file(),
              "approval_policy": None, "sandbox_mode": None, "project_trusted": False}
    if not cfg.is_file():
        return status
    try:
        text = cfg.read_text(encoding="utf-8")
    except OSError:
        return status
    m = re.search(r'(?m)^\s*approval_policy\s*=\s*"([^"]+)"', text)
    if m:
        status["approval_policy"] = m.group(1)
    m = re.search(r'(?m)^\s*sandbox_mode\s*=\s*"([^"]+)"', text)
    if m:
        status["sandbox_mode"] = m.group(1)
    rp = str(root.resolve())
    # A [projects."<root>"] header followed (before the next table) by trust_level = "trusted".
    hdr = re.search(r'(?m)^\s*\[projects\.\"' + re.escape(rp) + r'\"\]\s*$', text)
    if hdr:
        rest = text[hdr.end():]
        nxt = re.search(r'(?m)^\s*\[', rest)
        block = rest[: nxt.start()] if nxt else rest
        if re.search(r'(?m)^\s*trust_level\s*=\s*"trusted"', block):
            status["project_trusted"] = True
    return status


def codex_is_interactive(status: dict) -> bool:
    pol = status.get("approval_policy")
    # Default (no config / unset) is interactive `on-request`. `never` is the only non-prompting mode.
    if pol is None:
        return True
    return pol in ("untrusted", "on-request", "on-failure")


def codex_friction_signal(root: Path) -> dict | None:
    """The canonical `permission-friction` signal for Codex: an interactive, untrusted workspace
    keeps pausing for approval. Trust (or `approval_policy="never"`) clears it."""
    status = codex_permission_status(root)
    if status["project_trusted"]:
        return None
    if not codex_is_interactive(status):
        return None
    return {"signal": "permission-friction", "approval_policy": status["approval_policy"] or "on-request",
            "config": status["config"]}


def render_permission_hint(root: Path, status: dict) -> str:
    rp = str(root.resolve())
    return (
        "🏹 Celeborn advisor —> Codex still pauses for approval in this workspace "
        f"(approval_policy={status.get('approval_policy') or 'on-request'}, "
        f"trusted={status['project_trusted']}). Trust it once so Codex stops re-prompting — add to "
        f"{status['config']}:\n\n"
        f'    [projects."{rp}"]\n'
        f'    trust_level = "trusted"\n\n'
        "(or set `approval_policy = \"never\"` + `sandbox_mode = \"workspace-write\"` globally). "
        "Codex's lever is coarse — a workspace trust flag, not per-command rules like Claude Code."
    )


def cmd_permissions(args: argparse.Namespace) -> int:
    """Codex permission lever (the `permissions` analog of `celeborn permissions`). `--suggest`
    (default, read-only) prints the config.toml trust/approval hint; `--apply` appends the
    `[projects."<root>"]` trust block when it is absent (idempotent, never edits in place)."""
    root = Path(args.path or ".").resolve()
    ctx_root = find_context_root(root) or root
    status = codex_permission_status(ctx_root)
    if status["project_trusted"]:
        print(f"✓ Codex already trusts {ctx_root} (no approval friction). config: {status['config']}")
        return 0
    if not codex_is_interactive(status):
        print(f"✓ Codex approval_policy={status['approval_policy']} — non-interactive, no friction. "
              f"config: {status['config']}")
        return 0

    print(render_permission_hint(ctx_root, status))
    if not getattr(args, "apply", False):
        print(f"\nApply (append the trust block):  codex_celeborn.py permissions --apply --path {ctx_root}")
        return 0

    cfg = Path(status["config"])
    rp = str(ctx_root.resolve())
    header = f'[projects."{rp}"]'
    existing = cfg.read_text(encoding="utf-8") if cfg.is_file() else ""
    if header in existing:
        print(f"\n⚠ {header} already present in {cfg} — edit `trust_level` by hand to avoid a duplicate table.")
        return 1
    cfg.parent.mkdir(parents=True, exist_ok=True)
    sep = "" if (not existing or existing.endswith("\n\n")) else ("\n" if existing.endswith("\n") else "\n\n")
    with cfg.open("a", encoding="utf-8") as fh:
        fh.write(f'{sep}{header}\ntrust_level = "trusted"\n')
    print(f"\n✓ Appended trust block to {cfg} — Codex will stop pausing for approval in {ctx_root}.")
    return 0


def cmd_advise(args: argparse.Namespace) -> int:
    """Codex friction advisor (the `celeborn advise` analog). Prints the recommendation that applies
    right now, or a clean line when there is none. `--json` for the structured form."""
    root = Path(args.path or ".").resolve()
    ctx_root = find_context_root(root) or root
    sig = codex_friction_signal(ctx_root)
    recs = []
    if sig:
        status = codex_permission_status(ctx_root)
        recs.append({"intent": "reduce-permission-friction", "signal": sig,
                     "text": render_permission_hint(ctx_root, status), "channel": "config"})
    if getattr(args, "json", False):
        print(json.dumps({"harness": "codex", "recommendations": recs}, indent=2))
        return 0
    if not recs:
        print("✓ No Codex friction detected — nothing to recommend right now.")
        return 0
    print(f"🏹 Celeborn advisor (codex) — {len(recs)} recommendation(s):")
    for r in recs:
        print(f"  • [{r['intent']}] {r['text']}")
    return 0


# --------------------------------------------------------------------------- hooks

def hook_session_start(payload: dict) -> int:
    root = workspace_root(payload)
    sid = session_id(payload)
    ctx_root = find_context_root(root)
    if ctx_root is None:
        return 0

    ensure_agents_md(ctx_root)

    if sid:
        run_celeborn("record", "orient", "--session", sid, project=ctx_root)

    result = run_celeborn("status", project=ctx_root)
    status = (result.stdout or "").strip()
    if not status:
        return 0

    # Carry the advisor recommendation on the SAME injection channel as orient (plan deliverable #6:
    # the pending-file injection carries an advisor notice as well as the Hot tier).
    advice = ""
    sig = codex_friction_signal(ctx_root)
    if sig:
        advice = "\n\n## Celeborn advisor\n\n" + render_permission_hint(ctx_root, codex_permission_status(ctx_root))

    pending = ctx_root / ".context" / ORIENT_FILE
    pending.write_text(
        "# Celeborn Orient (Codex session start)\n\n"
        f"**Project root:** `{ctx_root}`\n\n"
        "Codex does not inject SessionStart hook stdout into the model. "
        "Read this file once, orient from it, then delete it.\n\n"
        "Kanban shorthand in this project: `wire tN` / `claim tN` = take card tN; "
        "`ship tN` = close it; `hydrate` = you are here.\n\n" + status + advice + "\n",
        encoding="utf-8",
    )
    print("## Celeborn memory (Orient load)\n")
    print(status)
    if advice:
        print(advice)
    return 0


def hook_user_prompt_submit(payload: dict) -> int:
    root = workspace_root(payload)
    sid = session_id(payload)
    ctx_root = find_context_root(root)
    if ctx_root is None:
        return 0

    rollout = find_rollout_file(sid, root)
    tokens = read_context_tokens(rollout)
    lines = []

    pending = ctx_root / ".context" / ORIENT_FILE
    if pending.is_file():
        lines.append(ORIENT_NUDGE.format(root=ctx_root))

    if tokens is not None:
        remind = run_celeborn(
            "remind",
            "--tokens", str(tokens),
            "--every", "50000",
            "--soft-limit", "150000",
            "--alarm-limit", "200000",
            "--alarm-every", "100000",
            "--clear-cmd", CODEX_RENEW_CMD,
            project=ctx_root,
        )
        msg = (remind.stdout or remind.stderr or "").strip()
        if msg:
            lines.append(msg)

    if sid:
        beat = run_celeborn("heartbeat", "--session", sid, project=ctx_root)
        beat_line = (beat.stdout or "").strip()
        if beat_line:
            lines.append(beat_line)

    if rollout is not None and rollout.is_file():
        dest = claude_transcript_path(sid or "session")
        convert_codex_transcript(rollout, sid or "session", dest)
        if tokens is not None:
            run_celeborn("record", "turn", "--tokens", str(tokens), project=ctx_root)

    if lines:
        print("\n".join(lines))
    return 0


def hook_stop(payload: dict) -> int:
    root = workspace_root(payload)
    sid = session_id(payload) or "session"
    rollout = find_rollout_file(sid if sid != "session" else session_id(payload), root)
    if rollout is None or not rollout.is_file():
        return 0

    dest = claude_transcript_path(sid)
    if convert_codex_transcript(rollout, sid, dest) == 0:
        return 0

    ctx_root = find_context_root(root)
    cap_args = ["capture", "--transcript", str(dest), "--session", sid, "--quiet", "--note"]
    if ctx_root is None:
        cap_args.append("--global")
    capture = run_celeborn(*cap_args, project=ctx_root)
    note = (capture.stdout or "").strip()
    if note:
        if note.startswith("{"):
            try:
                env = json.loads(note)
                msg = env.get("systemMessage")
                if msg:
                    print(msg)
                    return 0
            except json.JSONDecodeError:
                pass
        print(note)
    return 0


def hook_pre_compact(payload: dict) -> int:
    root = workspace_root(payload)
    ctx_root = find_context_root(root)
    if ctx_root is not None:
        run_celeborn("record", "compaction", project=ctx_root)
    print(PRECOMPACT_MSG)
    return 0


def hook_session_end(payload: dict) -> int:
    root = workspace_root(payload)
    ctx_root = find_context_root(root)
    if ctx_root is None:
        return 0
    run_celeborn("handoff", project=ctx_root)
    pending = ctx_root / ".context" / ORIENT_FILE
    if pending.is_file():
        pending.unlink(missing_ok=True)
    return 0


def hook_notify(payload: dict) -> int:
    """Codex's legacy `notify` program hook (fires once on `agent-turn-complete`). We treat it as a
    Stop equivalent: convert + capture the just-completed turn. argv may carry the JSON as the last
    arg rather than on stdin (see legacy_notify)."""
    if not payload:
        # legacy_notify appends the JSON as the final argv item.
        for arg in reversed(sys.argv):
            if arg.strip().startswith("{"):
                try:
                    payload = json.loads(arg)
                    break
                except json.JSONDecodeError:
                    continue
    if payload.get("type") not in (None, "agent-turn-complete"):
        return 0
    return hook_stop(payload)


# --------------------------------------------------------------------------- bootstrap / install / doctor

def active_session_for(root: Path) -> str | None:
    """Most recent rollout whose session_meta cwd matches `root` (best-effort, no live API)."""
    base = codex_home() / "sessions"
    if not base.is_dir():
        return None
    target = str(root.resolve())
    for rollout in sorted(base.glob("**/rollout-*.jsonl"), reverse=True)[:50]:
        try:
            with rollout.open("r", encoding="utf-8", errors="ignore") as fh:
                first = fh.readline()
        except OSError:
            continue
        try:
            obj = json.loads(first)
        except json.JSONDecodeError:
            continue
        payload = obj.get("payload") if isinstance(obj, dict) else None
        meta = payload if isinstance(payload, dict) else obj
        if str(meta.get("cwd") or "") == target:
            sid = meta.get("id") or ""
            if sid:
                return str(sid)
    return None


def cmd_bootstrap(args: argparse.Namespace) -> int:
    """Prime Celeborn memory without waiting for Codex hooks (orient file + AGENTS.md block)."""
    root = Path(args.path or ".").resolve()
    ctx_root = find_context_root(root)
    if ctx_root is None:
        print("No .context/ found — run `celeborn init` in your project first.", file=sys.stderr)
        return 1

    # Pin the harness in .celebornrc so any direct `celeborn` call in this repo (not just our hooks,
    # which already export CELEBORN_HARNESS) resolves CodexAdapter. Idempotent + best-effort.
    # --no-harness-pin lets a speculative caller skip the pin (parity with the grok bridge; core init
    # only wires Grok, so Codex is always a deliberate install today).
    if not getattr(args, "no_harness_pin", False):
        run_celeborn("harness", "codex", project=ctx_root)

    payload = {"cwd": str(ctx_root), "workspaceRoot": str(ctx_root)}
    sid = active_session_for(ctx_root)
    if sid:
        payload["session_id"] = sid
    hook_session_start(payload)
    pending = ctx_root / ".context" / ORIENT_FILE
    if pending.is_file():
        print(f"✓ wrote {pending.relative_to(ctx_root)} (read once on next Codex turn)")
    print(f"✓ ensured AGENTS.md Celeborn block in {ctx_root}")
    return 0


def cmd_install(args: argparse.Namespace) -> int:
    install_sh = MODULE_ROOT / "scripts" / "install.sh"
    if not install_sh.is_file():
        print(f"install script missing: {install_sh}", file=sys.stderr)
        return 1
    cmd = ["bash", str(install_sh)]
    project = getattr(args, "project", None)
    if project:
        cmd.extend(["--project", str(Path(project).resolve())])
    if getattr(args, "private", False):
        cmd.append("--private")
    if getattr(args, "public", False):
        cmd.append("--public")
    if getattr(args, "no_init", False):
        cmd.append("--no-init")
    return subprocess.run(cmd, check=False).returncode


def cmd_sync_agents(args: argparse.Namespace) -> int:
    root = Path(args.path or ".").resolve()
    ctx_root = find_context_root(root) or root
    if ensure_agents_md(ctx_root):
        print(f"✓ refreshed AGENTS.md Celeborn block in {ctx_root}")
    else:
        print(f"· AGENTS.md Celeborn block already current in {ctx_root}")
    return 0


def cmd_doctor(_args: argparse.Namespace) -> int:
    ok = True
    which = subprocess.run(["which", "celeborn"], capture_output=True, text=True)
    if which.returncode != 0:
        print("✗ celeborn not on PATH — run: uv tool install --editable <celeborn-clone>")
        ok = False
    else:
        print(f"✓ celeborn at {which.stdout.strip()}")
        ver = run_celeborn("version")
        print(f"  {ver.stdout.strip()}")

    home = codex_home()
    if home.is_dir():
        print(f"✓ Codex home {home}")
    else:
        print(f"· no {home} yet — Codex not installed or never run (the adapter still works once it is)")
    cfg = codex_config_path()
    print(f"{'✓' if cfg.is_file() else '·'} config {cfg}{'' if cfg.is_file() else ' (absent)'}")

    hooks = home / "hooks" / "celeborn.json"
    if hooks.is_file():
        print(f"✓ Codex hooks installed at {hooks}")
    else:
        print(f"· Codex hooks not installed — run: {MODULE_ROOT}/scripts/install.sh "
              "(or add the [hooks] table from hooks/celeborn.json to ~/.codex/config.toml)")

    sid = os.environ.get("CODEX_SESSION_ID", "") or os.environ.get("CODEX_THREAD_ID", "")
    root = Path(os.environ.get("CODEX_WORKSPACE_ROOT", Path.cwd()))
    rollout = find_rollout_file(sid, root) if sid else None
    if rollout:
        print(f"✓ rollout {rollout}")
        n = convert_codex_transcript(rollout, sid, claude_transcript_path(sid))
        print(f"  transcript bridge: {n} Claude-shaped line(s)")
    else:
        print("· no active CODEX_SESSION_ID (run from a Codex hook to test session resolution)")
    return 0 if ok else 1


def cmd_convert(args: argparse.Namespace) -> int:
    src = Path(args.source)
    if not src.is_file():
        print(f"source not found: {src}", file=sys.stderr)
        return 1
    dest = Path(args.dest) if args.dest else claude_transcript_path(args.session)
    n = convert_codex_transcript(src, args.session, dest)
    print(f"converted {n} line(s) → {dest}")
    return 0


HOOK_CMDS = {
    "session-start": hook_session_start,
    "user-prompt-submit": hook_user_prompt_submit,
    "stop": hook_stop,
    "pre-compact": hook_pre_compact,
    "session-end": hook_session_end,
    "notify": hook_notify,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Codex CLI adapter for Celeborn")
    sub = parser.add_subparsers(dest="cmd")

    for event in ("session-start", "user-prompt-submit", "stop", "pre-compact", "session-end", "notify"):
        sub.add_parser(event, help=f"Codex {event} hook entry point")

    sub.add_parser("doctor", help="verify celeborn + codex bridge health")
    boot = sub.add_parser("bootstrap", help="write orient-pending + AGENTS.md block without a hook reload")
    boot.add_argument("--path", default=".", help="project root (default: cwd)")
    boot.add_argument("--no-harness-pin", dest="no_harness_pin", action="store_true",
                      help="don't pin harness=codex in .celebornrc (for speculative wiring; parity with grok)")
    inst = sub.add_parser("install", help="install Codex hooks + optional celeborn init + bootstrap")
    inst.add_argument("--project", help="project root to init/bootstrap")
    inst.add_argument("--private", action="store_true")
    inst.add_argument("--public", action="store_true")
    inst.add_argument("--no-init", action="store_true")
    syn = sub.add_parser("sync-agents", help="refresh the managed Celeborn block in AGENTS.md")
    syn.add_argument("--path", default=".")
    cvt = sub.add_parser("convert", help="convert a Codex rollout .jsonl for celeborn capture")
    cvt.add_argument("source")
    cvt.add_argument("--session", default="manual")
    cvt.add_argument("--dest")
    perm = sub.add_parser("permissions", help="Codex approval/trust hint (config.toml lever)")
    perm.add_argument("--path", default=".")
    perm.add_argument("--suggest", action="store_true", help="preview the hint (default; read-only)")
    perm.add_argument("--apply", action="store_true", help="append the [projects.<root>] trust block")
    adv = sub.add_parser("advise", help="print the Codex friction recommendation that applies now")
    adv.add_argument("--path", default=".")
    adv.add_argument("--json", action="store_true")

    args = parser.parse_args(argv)
    if not args.cmd:
        parser.print_help()
        return 2
    if args.cmd in HOOK_CMDS:
        return HOOK_CMDS[args.cmd](read_stdin_json())
    return {
        "doctor": cmd_doctor,
        "bootstrap": cmd_bootstrap,
        "install": cmd_install,
        "sync-agents": cmd_sync_agents,
        "convert": cmd_convert,
        "permissions": cmd_permissions,
        "advise": cmd_advise,
    }[args.cmd](args)


if __name__ == "__main__":
    raise SystemExit(main())
